#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

###### racc/parser.rb begin
unless $".index 'racc/parser.rb'
$".push 'racc/parser.rb'
self.class.module_eval(<<'...end racc/parser.rb/module_eval...', 'racc/parser.rb', 1)
#
# $Id: 2bd697d1146b280d8d3878e21e556ef769484a37 $
#
# Copyright (c) 1999-2006 Minero Aoki
#
# This program is free software.
# You can distribute/modify this program under the same terms of ruby.
#
# As a special exception, when this code is copied by Racc
# into a Racc output file, you may use that output file
# without restriction.
#

require 'racc/info'

unless defined?(NotImplementedError)
  NotImplementedError = NotImplementError # :nodoc:
end

module Racc
  class ParseError < StandardError; end
end
unless defined?(::ParseError)
  ParseError = Racc::ParseError
end

# Racc is a LALR(1) parser generator.
# It is written in Ruby itself, and generates Ruby programs.
#
# == Command-line Reference
#
#     racc [-o<var>filename</var>] [--output-file=<var>filename</var>]
#          [-e<var>rubypath</var>] [--embedded=<var>rubypath</var>]
#          [-v] [--verbose]
#          [-O<var>filename</var>] [--log-file=<var>filename</var>]
#          [-g] [--debug]
#          [-E] [--embedded]
#          [-l] [--no-line-convert]
#          [-c] [--line-convert-all]
#          [-a] [--no-omit-actions]
#          [-C] [--check-only]
#          [-S] [--output-status]
#          [--version] [--copyright] [--help] <var>grammarfile</var>
#
# [+filename+]
#   Racc grammar file. Any extention is permitted.
# [-o+outfile+, --output-file=+outfile+]
#   A filename for output. default is <+filename+>.tab.rb
# [-O+filename+, --log-file=+filename+]
#   Place logging output in file +filename+.
#   Default log file name is <+filename+>.output.
# [-e+rubypath+, --executable=+rubypath+]
#   output executable file(mode 755). where +path+ is the Ruby interpreter.
# [-v, --verbose]
#   verbose mode. create +filename+.output file, like yacc's y.output file.
# [-g, --debug]
#   add debug code to parser class. To display debuggin information,
#   use this '-g' option and set @yydebug true in parser class.
# [-E, --embedded]
#   Output parser which doesn't need runtime files (racc/parser.rb).
# [-C, --check-only]
#   Check syntax of racc grammer file and quit.
# [-S, --output-status]
#   Print messages time to time while compiling.
# [-l, --no-line-convert]
#   turns off line number converting.
# [-c, --line-convert-all]
#   Convert line number of actions, inner, header and footer.
# [-a, --no-omit-actions]
#   Call all actions, even if an action is empty.
# [--version]
#   print Racc version and quit.
# [--copyright]
#   Print copyright and quit.
# [--help]
#   Print usage and quit.
#
# == Generating Parser Using Racc
#
# To compile Racc grammar file, simply type:
#
#   $ racc parse.y
#
# This creates Ruby script file "parse.tab.y". The -o option can change the output filename.
#
# == Writing A Racc Grammar File
#
# If you want your own parser, you have to write a grammar file.
# A grammar file contains the name of your parser class, grammar for the parser,
# user code, and anything else.
# When writing a grammar file, yacc's knowledge is helpful.
# If you have not used yacc before, Racc is not too difficult.
#
# Here's an example Racc grammar file.
#
#   class Calcparser
#   rule
#     target: exp { print val[0] }
#
#     exp: exp '+' exp
#        | exp '*' exp
#        | '(' exp ')'
#        | NUMBER
#   end
#
# Racc grammar files resemble yacc files.
# But (of course), this is Ruby code.
# yacc's $$ is the 'result', $0, $1... is
# an array called 'val', and $-1, $-2... is an array called '_values'.
#
# See the {Grammar File Reference}[rdoc-ref:lib/racc/rdoc/grammar.en.rdoc] for
# more information on grammar files.
#
# == Parser
#
# Then you must prepare the parse entry method. There are two types of
# parse methods in Racc, Racc::Parser#do_parse and Racc::Parser#yyparse
#
# Racc::Parser#do_parse is simple.
#
# It's yyparse() of yacc, and Racc::Parser#next_token is yylex().
# This method must returns an array like [TOKENSYMBOL, ITS_VALUE].
# EOF is [false, false].
# (TOKENSYMBOL is a Ruby symbol (taken from String#intern) by default.
# If you want to change this, see the grammar reference.
#
# Racc::Parser#yyparse is little complicated, but useful.
# It does not use Racc::Parser#next_token, instead it gets tokens from any iterator.
#
# For example, <code>yyparse(obj, :scan)</code> causes
# calling +obj#scan+, and you can return tokens by yielding them from +obj#scan+.
#
# == Debugging
#
# When debugging, "-v" or/and the "-g" option is helpful.
#
# "-v" creates verbose log file (.output).
# "-g" creates a "Verbose Parser".
# Verbose Parser prints the internal status when parsing.
# But it's _not_ automatic.
# You must use -g option and set +@yydebug+ to +true+ in order to get output.
# -g option only creates the verbose parser.
#
# === Racc reported syntax error.
#
# Isn't there too many "end"?
# grammar of racc file is changed in v0.10.
#
# Racc does not use '%' mark, while yacc uses huge number of '%' marks..
#
# === Racc reported "XXXX conflicts".
#
# Try "racc -v xxxx.y".
# It causes producing racc's internal log file, xxxx.output.
#
# === Generated parsers does not work correctly
#
# Try "racc -g xxxx.y".
# This command let racc generate "debugging parser".
# Then set @yydebug=true in your parser.
# It produces a working log of your parser.
#
# == Re-distributing Racc runtime
#
# A parser, which is created by Racc, requires the Racc runtime module;
# racc/parser.rb.
#
# Ruby 1.8.x comes with Racc runtime module,
# you need NOT distribute Racc runtime files.
#
# If you want to include the Racc runtime module with your parser.
# This can be done by using '-E' option:
#
#   $ racc -E -omyparser.rb myparser.y
#
# This command creates myparser.rb which `includes' Racc runtime.
# Only you must do is to distribute your parser file (myparser.rb).
#
# Note: parser.rb is LGPL, but your parser is not.
# Your own parser is completely yours.
module Racc

  unless defined?(Racc_No_Extentions)
    Racc_No_Extentions = false # :nodoc:
  end

  class Parser

    Racc_Runtime_Version = ::Racc::VERSION
    Racc_Runtime_Revision = '$Id: 2bd697d1146b280d8d3878e21e556ef769484a37 $'

    Racc_Runtime_Core_Version_R = ::Racc::VERSION
    Racc_Runtime_Core_Revision_R = '$Id: 2bd697d1146b280d8d3878e21e556ef769484a37 $'.split[1]
    begin
      if Object.const_defined?(:RUBY_ENGINE) and RUBY_ENGINE == 'jruby'
        require 'racc/cparse-jruby.jar'
        com.headius.racc.Cparse.new.load(JRuby.runtime, false)
      else
        require 'racc/cparse'
      end
    # Racc_Runtime_Core_Version_C  = (defined in extention)
      Racc_Runtime_Core_Revision_C = Racc_Runtime_Core_Id_C.split[2]
      unless new.respond_to?(:_racc_do_parse_c, true)
        raise LoadError, 'old cparse.so'
      end
      if Racc_No_Extentions
        raise LoadError, 'selecting ruby version of racc runtime core'
      end

      Racc_Main_Parsing_Routine    = :_racc_do_parse_c # :nodoc:
      Racc_YY_Parse_Method         = :_racc_yyparse_c # :nodoc:
      Racc_Runtime_Core_Version    = Racc_Runtime_Core_Version_C # :nodoc:
      Racc_Runtime_Core_Revision   = Racc_Runtime_Core_Revision_C # :nodoc:
      Racc_Runtime_Type            = 'c' # :nodoc:
    rescue LoadError
puts $!
puts $!.backtrace
      Racc_Main_Parsing_Routine    = :_racc_do_parse_rb
      Racc_YY_Parse_Method         = :_racc_yyparse_rb
      Racc_Runtime_Core_Version    = Racc_Runtime_Core_Version_R
      Racc_Runtime_Core_Revision   = Racc_Runtime_Core_Revision_R
      Racc_Runtime_Type            = 'ruby'
    end

    def Parser.racc_runtime_type # :nodoc:
      Racc_Runtime_Type
    end

    def _racc_setup
      @yydebug = false unless self.class::Racc_debug_parser
      @yydebug = false unless defined?(@yydebug)
      if @yydebug
        @racc_debug_out = $stderr unless defined?(@racc_debug_out)
        @racc_debug_out ||= $stderr
      end
      arg = self.class::Racc_arg
      arg[13] = true if arg.size < 14
      arg
    end

    def _racc_init_sysvars
      @racc_state  = [0]
      @racc_tstack = []
      @racc_vstack = []

      @racc_t = nil
      @racc_val = nil

      @racc_read_next = true

      @racc_user_yyerror = false
      @racc_error_status = 0
    end

    # The entry point of the parser. This method is used with #next_token.
    # If Racc wants to get token (and its value), calls next_token.
    #
    # Example:
    #     def parse
    #       @q = [[1,1],
    #             [2,2],
    #             [3,3],
    #             [false, '$']]
    #       do_parse
    #     end
    #
    #     def next_token
    #       @q.shift
    #     end
    def do_parse
      __send__(Racc_Main_Parsing_Routine, _racc_setup(), false)
    end

    # The method to fetch next token.
    # If you use #do_parse method, you must implement #next_token.
    #
    # The format of return value is [TOKEN_SYMBOL, VALUE].
    # +token-symbol+ is represented by Ruby's symbol by default, e.g. :IDENT
    # for 'IDENT'.  ";" (String) for ';'.
    #
    # The final symbol (End of file) must be false.
    def next_token
      raise NotImplementedError, "#{self.class}\#next_token is not defined"
    end

    def _racc_do_parse_rb(arg, in_debug)
      action_table, action_check, action_default, action_pointer,
      _,            _,            _,              _,
      _,            _,            token_table,    * = arg

      _racc_init_sysvars
      tok = act = i = nil

      catch(:racc_end_parse) {
        while true
          if i = action_pointer[@racc_state[-1]]
            if @racc_read_next
              if @racc_t != 0   # not EOF
                tok, @racc_val = next_token()
                unless tok      # EOF
                  @racc_t = 0
                else
                  @racc_t = (token_table[tok] or 1)   # error token
                end
                racc_read_token(@racc_t, tok, @racc_val) if @yydebug
                @racc_read_next = false
              end
            end
            i += @racc_t
            unless i >= 0 and
                   act = action_table[i] and
                   action_check[i] == @racc_state[-1]
              act = action_default[@racc_state[-1]]
            end
          else
            act = action_default[@racc_state[-1]]
          end
          while act = _racc_evalact(act, arg)
            ;
          end
        end
      }
    end

    # Another entry point for the parser.
    # If you use this method, you must implement RECEIVER#METHOD_ID method.
    #
    # RECEIVER#METHOD_ID is a method to get next token.
    # It must 'yield' the token, which format is [TOKEN-SYMBOL, VALUE].
    def yyparse(recv, mid)
      __send__(Racc_YY_Parse_Method, recv, mid, _racc_setup(), false)
    end

    def _racc_yyparse_rb(recv, mid, arg, c_debug)
      action_table, action_check, action_default, action_pointer,
      _,            _,            _,              _,
      _,            _,            token_table,    * = arg

      _racc_init_sysvars

      catch(:racc_end_parse) {
        until i = action_pointer[@racc_state[-1]]
          while act = _racc_evalact(action_default[@racc_state[-1]], arg)
            ;
          end
        end
        recv.__send__(mid) do |tok, val|
          unless tok
            @racc_t = 0
          else
            @racc_t = (token_table[tok] or 1)   # error token
          end
          @racc_val = val
          @racc_read_next = false

          i += @racc_t
          unless i >= 0 and
                 act = action_table[i] and
                 action_check[i] == @racc_state[-1]
            act = action_default[@racc_state[-1]]
          end
          while act = _racc_evalact(act, arg)
            ;
          end

          while !(i = action_pointer[@racc_state[-1]]) ||
                ! @racc_read_next ||
                @racc_t == 0  # $
            unless i and i += @racc_t and
                   i >= 0 and
                   act = action_table[i] and
                   action_check[i] == @racc_state[-1]
              act = action_default[@racc_state[-1]]
            end
            while act = _racc_evalact(act, arg)
              ;
            end
          end
        end
      }
    end

    ###
    ### common
    ###

    def _racc_evalact(act, arg)
      action_table, action_check, _, action_pointer,
      _,            _,            _, _,
      _,            _,            _, shift_n,
      reduce_n,     * = arg
      nerr = 0   # tmp

      if act > 0 and act < shift_n
        #
        # shift
        #
        if @racc_error_status > 0
          @racc_error_status -= 1 unless @racc_t <= 1 # error token or EOF
        end
        @racc_vstack.push @racc_val
        @racc_state.push act
        @racc_read_next = true
        if @yydebug
          @racc_tstack.push @racc_t
          racc_shift @racc_t, @racc_tstack, @racc_vstack
        end

      elsif act < 0 and act > -reduce_n
        #
        # reduce
        #
        code = catch(:racc_jump) {
          @racc_state.push _racc_do_reduce(arg, act)
          false
        }
        if code
          case code
          when 1 # yyerror
            @racc_user_yyerror = true   # user_yyerror
            return -reduce_n
          when 2 # yyaccept
            return shift_n
          else
            raise '[Racc Bug] unknown jump code'
          end
        end

      elsif act == shift_n
        #
        # accept
        #
        racc_accept if @yydebug
        throw :racc_end_parse, @racc_vstack[0]

      elsif act == -reduce_n
        #
        # error
        #
        case @racc_error_status
        when 0
          unless arg[21]    # user_yyerror
            nerr += 1
            on_error @racc_t, @racc_val, @racc_vstack
          end
        when 3
          if @racc_t == 0   # is $
            # We're at EOF, and another error occurred immediately after
            # attempting auto-recovery
            throw :racc_end_parse, nil
          end
          @racc_read_next = true
        end
        @racc_user_yyerror = false
        @racc_error_status = 3
        while true
          if i = action_pointer[@racc_state[-1]]
            i += 1   # error token
            if  i >= 0 and
                (act = action_table[i]) and
                action_check[i] == @racc_state[-1]
              break
            end
          end
          throw :racc_end_parse, nil if @racc_state.size <= 1
          @racc_state.pop
          @racc_vstack.pop
          if @yydebug
            @racc_tstack.pop
            racc_e_pop @racc_state, @racc_tstack, @racc_vstack
          end
        end
        return act

      else
        raise "[Racc Bug] unknown action #{act.inspect}"
      end

      racc_next_state(@racc_state[-1], @racc_state) if @yydebug

      nil
    end

    def _racc_do_reduce(arg, act)
      _,          _,            _,            _,
      goto_table, goto_check,   goto_default, goto_pointer,
      nt_base,    reduce_table, _,            _,
      _,          use_result,   * = arg

      state = @racc_state
      vstack = @racc_vstack
      tstack = @racc_tstack

      i = act * -3
      len       = reduce_table[i]
      reduce_to = reduce_table[i+1]
      method_id = reduce_table[i+2]
      void_array = []

      tmp_t = tstack[-len, len] if @yydebug
      tmp_v = vstack[-len, len]
      tstack[-len, len] = void_array if @yydebug
      vstack[-len, len] = void_array
      state[-len, len]  = void_array

      # tstack must be updated AFTER method call
      if use_result
        vstack.push __send__(method_id, tmp_v, vstack, tmp_v[0])
      else
        vstack.push __send__(method_id, tmp_v, vstack)
      end
      tstack.push reduce_to

      racc_reduce(tmp_t, reduce_to, tstack, vstack) if @yydebug

      k1 = reduce_to - nt_base
      if i = goto_pointer[k1]
        i += state[-1]
        if i >= 0 and (curstate = goto_table[i]) and goto_check[i] == k1
          return curstate
        end
      end
      goto_default[k1]
    end

    # This method is called when a parse error is found.
    #
    # ERROR_TOKEN_ID is an internal ID of token which caused error.
    # You can get string representation of this ID by calling
    # #token_to_str.
    #
    # ERROR_VALUE is a value of error token.
    #
    # value_stack is a stack of symbol values.
    # DO NOT MODIFY this object.
    #
    # This method raises ParseError by default.
    #
    # If this method returns, parsers enter "error recovering mode".
    def on_error(t, val, vstack)
      raise ParseError, sprintf("\nparse error on value %s (%s)",
                                val.inspect, token_to_str(t) || '?')
    end

    # Enter error recovering mode.
    # This method does not call #on_error.
    def yyerror
      throw :racc_jump, 1
    end

    # Exit parser.
    # Return value is Symbol_Value_Stack[0].
    def yyaccept
      throw :racc_jump, 2
    end

    # Leave error recovering mode.
    def yyerrok
      @racc_error_status = 0
    end

    # For debugging output
    def racc_read_token(t, tok, val)
      @racc_debug_out.print 'read    '
      @racc_debug_out.print tok.inspect, '(', racc_token2str(t), ') '
      @racc_debug_out.puts val.inspect
      @racc_debug_out.puts
    end

    def racc_shift(tok, tstack, vstack)
      @racc_debug_out.puts "shift   #{racc_token2str tok}"
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_reduce(toks, sim, tstack, vstack)
      out = @racc_debug_out
      out.print 'reduce '
      if toks.empty?
        out.print ' <none>'
      else
        toks.each {|t| out.print ' ', racc_token2str(t) }
      end
      out.puts " --> #{racc_token2str(sim)}"
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_accept
      @racc_debug_out.puts 'accept'
      @racc_debug_out.puts
    end

    def racc_e_pop(state, tstack, vstack)
      @racc_debug_out.puts 'error recovering mode: pop token'
      racc_print_states state
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_next_state(curstate, state)
      @racc_debug_out.puts  "goto    #{curstate}"
      racc_print_states state
      @racc_debug_out.puts
    end

    def racc_print_stacks(t, v)
      out = @racc_debug_out
      out.print '        ['
      t.each_index do |i|
        out.print ' (', racc_token2str(t[i]), ' ', v[i].inspect, ')'
      end
      out.puts ' ]'
    end

    def racc_print_states(s)
      out = @racc_debug_out
      out.print '        ['
      s.each {|st| out.print ' ', st }
      out.puts ' ]'
    end

    def racc_token2str(tok)
      self.class::Racc_token_to_s_table[tok] or
          raise "[Racc Bug] can't convert token #{tok} to string"
    end

    # Convert internal ID of token symbol to the string.
    def token_to_str(t)
      self.class::Racc_token_to_s_table[t]
    end

  end

end

...end racc/parser.rb/module_eval...
end
###### racc/parser.rb end


require_relative 'Lexer'
require_relative 'AST_yo'


class ErrorSintactico < RuntimeError
  def initialize(token)
    @token = token
  end

  def to_s
    "Error de sintaxis en linea #{@token.linea}, columna #{@token.columna}, token '#{@token.contenido}' inesperado."
  end
end

class Parser < Racc::Parser

module_eval(<<'...end Parser.y/module_eval...', 'Parser.y', 189)

    def initialize(lexer)
      @lexer = lexer
      @yydebug = true
      super()
    end 

    def on_error(id, token, stack)
      raise ErrorSintactico.new(token)
    end

    def errorEncontrado(token)
      raise ErrorSintactico.new(token)
    end

    def next_token
      @lexer.shift
    end

    def parse
      do_parse
    end
...end Parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    20,   102,    21,    58,   104,    38,   103,    19,   105,   127,
    25,    44,    93,    17,    31,    32,    30,    33,    26,    41,
    76,    44,    16,   113,    18,     4,    12,    13,   132,     5,
    22,   115,    10,     8,   nil,   nil,    20,    14,    21,     6,
   nil,     7,     9,    19,    25,   nil,   nil,    11,    15,    17,
    30,    33,    26,   nil,   nil,   nil,   nil,   nil,    16,   nil,
    18,     4,    12,    13,   nil,     5,   nil,   nil,    10,     8,
   nil,   nil,    20,    14,    21,     6,   nil,     7,     9,    19,
    25,   nil,   nil,    11,    15,    17,    30,    33,    26,   nil,
   nil,   nil,   nil,   nil,    16,   nil,    18,     4,    12,    13,
   nil,     5,   129,   nil,    10,     8,   nil,   nil,    20,    14,
    21,     6,   nil,     7,     9,    19,   nil,   nil,    25,    11,
    15,    17,    31,    32,    30,    33,    26,   nil,   nil,   nil,
    16,   nil,    18,   nil,    12,    13,    20,   102,    21,   nil,
   104,    38,   103,    19,   105,    14,    25,   nil,   nil,    17,
    31,    32,    30,    33,    26,    11,    15,   nil,    16,   nil,
    18,     4,    12,    13,   nil,     5,   nil,   nil,    10,     8,
   nil,   nil,    20,    14,    21,     6,   nil,     7,     9,    19,
    20,   nil,    21,    11,    15,    17,   nil,    19,    20,   nil,
    21,   nil,   nil,    17,    16,    19,    18,   nil,    12,    13,
   nil,    17,    16,   nil,    18,   nil,    12,    13,   nil,    14,
    16,   nil,    18,   nil,    12,    13,    20,    14,    21,    11,
    15,   nil,   nil,    19,    20,    14,    21,    11,    15,    17,
   nil,    19,    20,   nil,    21,    11,    15,    17,    16,    19,
    18,   nil,    12,    13,   nil,    17,    16,   nil,    18,   nil,
    12,    13,   nil,    14,    16,   nil,    18,   nil,    12,    13,
    20,    14,    21,    11,    15,   nil,   nil,    19,    20,    14,
    21,    11,    15,    17,   nil,    19,    20,   nil,    21,    11,
    15,    17,    16,    19,    18,   nil,    12,    13,   nil,    17,
    16,   nil,    18,   nil,    12,    13,   nil,    14,    16,   nil,
    18,   nil,    12,    13,    20,    14,    21,    11,    15,   nil,
   nil,    19,    20,    14,    21,    11,    15,    17,   nil,    19,
   nil,   nil,   nil,    11,    15,    17,    16,   nil,    18,   nil,
    12,    13,   nil,   nil,    16,   nil,    18,   nil,    12,    13,
    20,    14,    21,   nil,   nil,    38,   nil,    19,   nil,    14,
    25,    11,    15,    17,    31,    32,    30,    33,    26,    11,
    15,   nil,    16,   nil,    18,     4,    12,    13,   nil,     5,
   nil,   nil,    10,     8,   nil,   nil,    20,    14,    21,     6,
   nil,     7,     9,    19,    20,   nil,    21,    11,    15,    17,
   nil,    19,    20,   nil,    21,   nil,   nil,    17,    16,    19,
    18,   nil,    12,    13,   nil,    17,    16,   nil,    18,   nil,
    12,    13,   nil,    14,    16,   nil,    18,   nil,    12,    13,
    20,    14,    21,    11,    15,   nil,   nil,    19,    20,    14,
    21,    11,    15,    17,   nil,    19,    20,   nil,    21,    11,
    15,    17,    16,    19,    18,   nil,    12,    13,   nil,    17,
    16,   nil,    18,   nil,    12,    13,   nil,    14,    16,   nil,
    18,   nil,    12,    13,    20,    14,    21,    11,    15,   nil,
   nil,    19,    20,    14,    21,    11,    15,    17,   nil,    19,
    20,   nil,    21,    11,    15,    17,    16,    19,    18,   nil,
    12,    13,   nil,    17,    16,   nil,    18,   nil,    12,    13,
   nil,    14,    16,   nil,    18,   nil,    12,    13,    20,    14,
    21,    11,    15,   nil,   nil,    19,    20,    14,    21,    11,
    15,    17,   nil,    19,    20,   nil,    21,    11,    15,    17,
    16,    19,    18,   nil,    12,    13,   nil,    17,    16,   nil,
    18,   nil,    12,    13,   nil,    14,    16,   nil,    18,   nil,
    12,    13,    20,    14,    21,    11,    15,   nil,   nil,    19,
    20,    14,    21,    11,    15,    17,   nil,    19,    20,   nil,
    21,    11,    15,    17,    16,    19,    18,   nil,    12,    13,
   nil,    17,    16,   nil,    18,   nil,    12,    13,   nil,    14,
    16,   nil,    18,   nil,    12,    13,    20,    14,    21,    11,
    15,   nil,   nil,    19,    20,    14,    21,    11,    15,    17,
   nil,    19,    20,   nil,    21,    11,    15,    17,    16,    19,
    18,   nil,    12,    13,   nil,    17,    16,   nil,    18,   nil,
    12,    13,   nil,    14,    16,   nil,    18,   nil,    12,    13,
    20,    14,    21,    11,    15,   nil,   nil,    19,   nil,    14,
   nil,    11,    15,    17,   nil,   125,   nil,   nil,   nil,    11,
    15,   nil,    16,   nil,    18,   nil,    12,    13,    20,   nil,
    21,   nil,   nil,   nil,   nil,    19,   nil,    14,   nil,   nil,
   nil,    17,   nil,   nil,   nil,   nil,   nil,    11,    15,   nil,
    16,   nil,    18,     4,    12,    13,   nil,     5,    80,   nil,
    10,     8,   nil,   nil,    20,    14,    21,     6,   nil,     7,
     9,    19,   nil,   nil,   nil,    11,    15,    17,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    16,   nil,    18,     4,
    12,    13,   nil,     5,   124,   nil,    10,     8,   nil,   nil,
    20,    14,    21,     6,   nil,     7,     9,    19,   nil,   nil,
   nil,    11,    15,    17,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    16,   nil,    18,     4,    12,    13,   nil,     5,
   nil,   nil,    10,     8,   nil,   nil,    20,    14,    21,     6,
   nil,     7,     9,    19,    20,   nil,    21,    11,    15,    17,
   nil,    19,    20,   nil,    21,   nil,   nil,    17,    16,    19,
    18,   nil,    12,    13,   nil,    17,    16,   nil,    18,   nil,
    12,    13,   nil,    14,    16,   nil,    18,   nil,    12,    13,
    20,    14,    21,    11,    15,   nil,   nil,    19,   nil,    14,
   nil,    11,    15,    17,   nil,   nil,   nil,   nil,   nil,    11,
    15,   nil,    16,   nil,    18,   nil,    12,    13,    20,   nil,
    21,   nil,   nil,   nil,   nil,    19,   nil,    14,   nil,   nil,
   nil,    17,   nil,   nil,   nil,   nil,   nil,    11,    15,   nil,
    16,   nil,    18,     4,    12,    13,   nil,     5,   111,   nil,
    10,     8,   nil,   nil,   nil,    14,   nil,     6,    38,     7,
     9,   nil,   nil,    25,   nil,    11,    15,    31,    32,    30,
    33,    26,    41,    42,   nil,    34,    35,    36,    39,    40,
    37,    27,    28,    20,    29,    21,   nil,   nil,   nil,   nil,
    19,   nil,   nil,   nil,   nil,   nil,    17,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    16,   110,    18,     4,    12,
    13,   nil,     5,   109,   nil,    10,     8,   nil,   108,    20,
    14,    21,     6,   nil,     7,     9,    19,    20,   nil,    21,
    11,    15,    17,   nil,    19,   nil,   nil,   nil,   nil,   nil,
    17,    16,   nil,    18,   nil,    12,    13,   nil,   nil,    16,
   nil,    18,   nil,    12,    13,    20,    14,    21,   nil,   nil,
   nil,   nil,    19,   nil,    14,   nil,    11,    15,    17,   nil,
   nil,   nil,   nil,   nil,    11,    15,   nil,    16,   nil,    18,
     4,    12,    13,   nil,     5,   134,   nil,    10,     8,   nil,
   nil,    20,    14,    21,     6,   nil,     7,     9,    19,   nil,
   nil,   nil,    11,    15,    17,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    16,   nil,    18,     4,    12,    13,   nil,
     5,   100,   nil,    10,     8,   nil,   nil,    20,    14,    21,
     6,   nil,     7,     9,    19,   nil,   nil,   nil,    11,    15,
    17,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    16,
   nil,    18,     4,    12,    13,   nil,     5,   nil,   nil,    10,
     8,   nil,   nil,    20,    14,    21,     6,   nil,     7,     9,
    19,   nil,   nil,   nil,    11,    15,    17,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    16,   nil,    18,   nil,    12,
    13,    20,   nil,    21,   nil,   nil,   nil,   nil,    19,   nil,
    14,   nil,   nil,   nil,    17,   nil,   nil,   nil,   nil,   nil,
    11,    15,   nil,    16,   nil,    18,     4,    12,    13,   nil,
     5,   nil,   nil,    10,     8,   nil,   nil,    20,    14,    21,
     6,   nil,     7,     9,    19,   nil,   nil,   nil,    11,    15,
    17,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    16,
   nil,    18,     4,    12,    13,   nil,     5,   nil,   nil,    10,
     8,   nil,   nil,   nil,    14,   nil,     6,    38,     7,     9,
   nil,   nil,    25,   nil,    11,    15,    31,    32,    30,    33,
    26,    41,    42,   nil,    34,    35,    36,    39,    40,    37,
    27,    28,   nil,    29,   nil,   nil,   nil,   114,    38,   nil,
   nil,   nil,   nil,    25,   nil,   nil,   nil,    31,    32,    30,
    33,    26,    41,    42,    85,    34,    35,    36,    39,    40,
    37,    27,    28,   nil,    29,    95,    38,   nil,   nil,   nil,
   nil,    25,   nil,   nil,    94,    31,    32,    30,    33,    26,
    41,    42,   nil,    34,    35,    36,    39,    40,    37,    27,
    28,    38,    29,   nil,   nil,   nil,    25,   123,   nil,   nil,
    31,    32,    30,    33,    26,    41,    42,   nil,    34,    35,
    36,    39,    40,    37,    27,    28,   nil,    29,    38,    24,
   nil,   nil,   nil,    25,   nil,   nil,    23,    31,    32,    30,
    33,    26,    41,    42,   nil,    34,    35,    36,    39,    40,
    37,    27,    28,   nil,    29,    38,    83,   nil,   nil,   nil,
    25,   nil,   nil,   nil,    31,    32,    30,    33,    26,    41,
    42,   nil,    34,    35,    36,    39,    40,    37,    27,    28,
    38,    29,   nil,   nil,   nil,    25,   nil,    84,   nil,    31,
    32,    30,    33,    26,    41,    42,   nil,    34,    35,    36,
    39,    40,    37,    27,    28,    38,    29,   nil,   nil,   nil,
    25,   131,   nil,   nil,    31,    32,    30,    33,    26,    41,
    42,   nil,    34,    35,    36,    39,    40,    37,    27,    28,
    38,    29,   nil,   nil,   nil,    25,   117,   nil,   nil,    31,
    32,    30,    33,    26,    41,    42,   nil,    34,    35,    36,
    39,    40,    37,    27,    28,    38,    29,   nil,   nil,   nil,
   121,   nil,   122,   nil,    31,    32,    30,    33,    26,    41,
    42,   nil,    34,    35,    36,    39,    40,    37,    27,    28,
   nil,    29,    38,    82,   nil,   nil,   nil,    25,   nil,   nil,
   nil,    31,    32,    30,    33,    26,    41,    42,   nil,    34,
    35,    36,    39,    40,    37,    27,    28,    38,    29,   nil,
   nil,   nil,    25,   nil,    86,   nil,    31,    32,    30,    33,
    26,    41,    42,   nil,    34,    35,    36,    39,    40,    37,
    27,    28,    38,    29,   nil,   nil,   nil,    25,    90,   nil,
   nil,    31,    32,    30,    33,    26,    41,    42,   nil,    34,
    35,    36,    39,    40,    37,    27,    28,    38,    29,   nil,
   nil,   nil,    25,    88,   nil,   nil,    31,    32,    30,    33,
    26,    41,    42,   nil,    34,    35,    36,    39,    40,    37,
    27,    28,   nil,    29,    38,    89,   nil,   nil,   nil,    25,
   nil,   nil,   nil,    31,    32,    30,    33,    26,    41,    42,
   nil,    34,    35,    36,    39,    40,    37,    27,    28,    38,
    29,   nil,   nil,    87,    25,   nil,   nil,   nil,    31,    32,
    30,    33,    26,    41,    42,   nil,    34,    35,    36,    39,
    40,    37,    27,    28,    38,    29,   nil,   nil,   nil,    25,
   nil,   nil,   nil,    31,    32,    30,    33,    26,    41,    42,
   nil,    34,    35,    36,    39,    40,    37,    27,    28,    38,
   nil,   nil,   nil,   nil,    25,   nil,   nil,   nil,    31,    32,
    30,    33,    26,    41,    42,   nil,    34,    35,    36,    39,
    40,    37,    27,    28,    38,   nil,   nil,   nil,   nil,    25,
   nil,   nil,   nil,    31,    32,    30,    33,    26,    41,    42,
   nil,    34,    35,    36,    39,    40,    37,    38,   nil,   nil,
   nil,   nil,    25,   nil,   nil,   nil,    31,    32,    30,    33,
    26,    41,    42,   nil,    38,   -56,   -56,   -56,   -56,    25,
   nil,   nil,   nil,    31,    32,    30,    33,    26,    41,    42,
   nil,    38,    35,    36,    39,    40,    25,   nil,   nil,   nil,
    31,    32,    30,    33,    26,    41,    42,   nil,    38,   -56,
   -56,   -56,   -56,    25,   nil,   nil,   nil,    31,    32,    30,
    33,    26,    41,    42,   nil,    38,   -56,   -56,   -56,   -56,
    25,   nil,   nil,   nil,    31,    32,    30,    33,    26,    41,
    42,   nil,    38,   -56,   -56,   -56,   -56,    25,   nil,   nil,
   nil,    31,    32,    30,    33,    26,    41,    42,   nil,   nil,
    35,    36,    39,    40 ]

racc_action_check = [
     0,   127,     0,    22,   127,    75,   127,     0,   127,   123,
    75,     4,    78,     0,    75,    75,    75,    75,    75,    75,
    43,    77,     0,   105,     0,     0,     0,     0,   131,     0,
     1,   108,     0,     0,   nil,   nil,   132,     0,   132,     0,
   nil,     0,     0,   132,    65,   nil,   nil,     0,     0,   132,
    65,    65,    65,   nil,   nil,   nil,   nil,   nil,   132,   nil,
   132,   132,   132,   132,   nil,   132,   nil,   nil,   132,   132,
   nil,   nil,   126,   132,   126,   132,   nil,   132,   132,   126,
    64,   nil,   nil,   132,   132,   126,    64,    64,    64,   nil,
   nil,   nil,   nil,   nil,   126,   nil,   126,   126,   126,   126,
   nil,   126,   126,   nil,   126,   126,   nil,   nil,   125,   126,
   125,   126,   nil,   126,   126,   125,   nil,   nil,    71,   126,
   126,   125,    71,    71,    71,    71,    71,   nil,   nil,   nil,
   125,   nil,   125,   nil,   125,   125,     5,    93,     5,   nil,
    93,    74,    93,     5,    93,   125,    74,   nil,   nil,     5,
    74,    74,    74,    74,    74,   125,   125,   nil,     5,   nil,
     5,     5,     5,     5,   nil,     5,   nil,   nil,     5,     5,
   nil,   nil,     6,     5,     6,     5,   nil,     5,     5,     6,
     7,   nil,     7,     5,     5,     6,   nil,     7,     8,   nil,
     8,   nil,   nil,     7,     6,     8,     6,   nil,     6,     6,
   nil,     8,     7,   nil,     7,   nil,     7,     7,   nil,     6,
     8,   nil,     8,   nil,     8,     8,     9,     7,     9,     6,
     6,   nil,   nil,     9,    10,     8,    10,     7,     7,     9,
   nil,    10,    16,   nil,    16,     8,     8,    10,     9,    16,
     9,   nil,     9,     9,   nil,    16,    10,   nil,    10,   nil,
    10,    10,   nil,     9,    16,   nil,    16,   nil,    16,    16,
    17,    10,    17,     9,     9,   nil,   nil,    17,    18,    16,
    18,    10,    10,    17,   nil,    18,    19,   nil,    19,    16,
    16,    18,    17,    19,    17,   nil,    17,    17,   nil,    19,
    18,   nil,    18,   nil,    18,    18,   nil,    17,    19,   nil,
    19,   nil,    19,    19,    20,    18,    20,    17,    17,   nil,
   nil,    20,    21,    19,    21,    18,    18,    20,   nil,    21,
   nil,   nil,   nil,    19,    19,    21,    20,   nil,    20,   nil,
    20,    20,   nil,   nil,    21,   nil,    21,   nil,    21,    21,
   122,    20,   122,   nil,   nil,    53,   nil,   122,   nil,    21,
    53,    20,    20,   122,    53,    53,    53,    53,    53,    21,
    21,   nil,   122,   nil,   122,   122,   122,   122,   nil,   122,
   nil,   nil,   122,   122,   nil,   nil,    23,   122,    23,   122,
   nil,   122,   122,    23,    25,   nil,    25,   122,   122,    23,
   nil,    25,    26,   nil,    26,   nil,   nil,    25,    23,    26,
    23,   nil,    23,    23,   nil,    26,    25,   nil,    25,   nil,
    25,    25,   nil,    23,    26,   nil,    26,   nil,    26,    26,
    29,    25,    29,    23,    23,   nil,   nil,    29,    30,    26,
    30,    25,    25,    29,   nil,    30,    31,   nil,    31,    26,
    26,    30,    29,    31,    29,   nil,    29,    29,   nil,    31,
    30,   nil,    30,   nil,    30,    30,   nil,    29,    31,   nil,
    31,   nil,    31,    31,    32,    30,    32,    29,    29,   nil,
   nil,    32,    33,    31,    33,    30,    30,    32,   nil,    33,
    34,   nil,    34,    31,    31,    33,    32,    34,    32,   nil,
    32,    32,   nil,    34,    33,   nil,    33,   nil,    33,    33,
   nil,    32,    34,   nil,    34,   nil,    34,    34,    35,    33,
    35,    32,    32,   nil,   nil,    35,    36,    34,    36,    33,
    33,    35,   nil,    36,    37,   nil,    37,    34,    34,    36,
    35,    37,    35,   nil,    35,    35,   nil,    37,    36,   nil,
    36,   nil,    36,    36,   nil,    35,    37,   nil,    37,   nil,
    37,    37,    38,    36,    38,    35,    35,   nil,   nil,    38,
    39,    37,    39,    36,    36,    38,   nil,    39,    40,   nil,
    40,    37,    37,    39,    38,    40,    38,   nil,    38,    38,
   nil,    40,    39,   nil,    39,   nil,    39,    39,   nil,    38,
    40,   nil,    40,   nil,    40,    40,    41,    39,    41,    38,
    38,   nil,   nil,    41,    42,    40,    42,    39,    39,    41,
   nil,    42,   121,   nil,   121,    40,    40,    42,    41,   121,
    41,   nil,    41,    41,   nil,   121,    42,   nil,    42,   nil,
    42,    42,   nil,    41,   121,   nil,   121,   nil,   121,   121,
    44,    42,    44,    41,    41,   nil,   nil,    44,   nil,   121,
   nil,    42,    42,    44,   nil,   121,   nil,   nil,   nil,   121,
   121,   nil,    44,   nil,    44,   nil,    44,    44,    45,   nil,
    45,   nil,   nil,   nil,   nil,    45,   nil,    44,   nil,   nil,
   nil,    45,   nil,   nil,   nil,   nil,   nil,    44,    44,   nil,
    45,   nil,    45,    45,    45,    45,   nil,    45,    45,   nil,
    45,    45,   nil,   nil,   120,    45,   120,    45,   nil,    45,
    45,   120,   nil,   nil,   nil,    45,    45,   120,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   120,   nil,   120,   120,
   120,   120,   nil,   120,   120,   nil,   120,   120,   nil,   nil,
   115,   120,   115,   120,   nil,   120,   120,   115,   nil,   nil,
   nil,   120,   120,   115,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   115,   nil,   115,   115,   115,   115,   nil,   115,
   nil,   nil,   115,   115,   nil,   nil,   114,   115,   114,   115,
   nil,   115,   115,   114,   113,   nil,   113,   115,   115,   114,
   nil,   113,   110,   nil,   110,   nil,   nil,   113,   114,   110,
   114,   nil,   114,   114,   nil,   110,   113,   nil,   113,   nil,
   113,   113,   nil,   114,   110,   nil,   110,   nil,   110,   110,
    99,   113,    99,   114,   114,   nil,   nil,    99,   nil,   110,
   nil,   113,   113,    99,   nil,   nil,   nil,   nil,   nil,   110,
   110,   nil,    99,   nil,    99,   nil,    99,    99,    98,   nil,
    98,   nil,   nil,   nil,   nil,    98,   nil,    99,   nil,   nil,
   nil,    98,   nil,   nil,   nil,   nil,   nil,    99,    99,   nil,
    98,   nil,    98,    98,    98,    98,   nil,    98,    98,   nil,
    98,    98,   nil,   nil,   nil,    98,   nil,    98,    97,    98,
    98,   nil,   nil,    97,   nil,    98,    98,    97,    97,    97,
    97,    97,    97,    97,   nil,    97,    97,    97,    97,    97,
    97,    97,    97,    96,    97,    96,   nil,   nil,   nil,   nil,
    96,   nil,   nil,   nil,   nil,   nil,    96,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    96,    97,    96,    96,    96,
    96,   nil,    96,    96,   nil,    96,    96,   nil,    96,    95,
    96,    95,    96,   nil,    96,    96,    95,    94,   nil,    94,
    96,    96,    95,   nil,    94,   nil,   nil,   nil,   nil,   nil,
    94,    95,   nil,    95,   nil,    95,    95,   nil,   nil,    94,
   nil,    94,   nil,    94,    94,   133,    95,   133,   nil,   nil,
   nil,   nil,   133,   nil,    94,   nil,    95,    95,   133,   nil,
   nil,   nil,   nil,   nil,    94,    94,   nil,   133,   nil,   133,
   133,   133,   133,   nil,   133,   133,   nil,   133,   133,   nil,
   nil,    91,   133,    91,   133,   nil,   133,   133,    91,   nil,
   nil,   nil,   133,   133,    91,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    91,   nil,    91,    91,    91,    91,   nil,
    91,    91,   nil,    91,    91,   nil,   nil,    86,    91,    86,
    91,   nil,    91,    91,    86,   nil,   nil,   nil,    91,    91,
    86,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    86,
   nil,    86,    86,    86,    86,   nil,    86,   nil,   nil,    86,
    86,   nil,   nil,    85,    86,    85,    86,   nil,    86,    86,
    85,   nil,   nil,   nil,    86,    86,    85,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    85,   nil,    85,   nil,    85,
    85,    84,   nil,    84,   nil,   nil,   nil,   nil,    84,   nil,
    85,   nil,   nil,   nil,    84,   nil,   nil,   nil,   nil,   nil,
    85,    85,   nil,    84,   nil,    84,    84,    84,    84,   nil,
    84,   nil,   nil,    84,    84,   nil,   nil,    76,    84,    76,
    84,   nil,    84,    84,    76,   nil,   nil,   nil,    84,    84,
    76,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    76,
   nil,    76,    76,    76,    76,   nil,    76,   nil,   nil,    76,
    76,   nil,   nil,   nil,    76,   nil,    76,    50,    76,    76,
   nil,   nil,    50,   nil,    76,    76,    50,    50,    50,    50,
    50,    50,    50,   nil,    50,    50,    50,    50,    50,    50,
    50,    50,   nil,    50,   nil,   nil,   nil,   106,   106,   nil,
   nil,   nil,   nil,   106,   nil,   nil,   nil,   106,   106,   106,
   106,   106,   106,   106,    50,   106,   106,   106,   106,   106,
   106,   106,   106,   nil,   106,    79,    79,   nil,   nil,   nil,
   nil,    79,   nil,   nil,    79,    79,    79,    79,    79,    79,
    79,    79,   nil,    79,    79,    79,    79,    79,    79,    79,
    79,   118,    79,   nil,   nil,   nil,   118,   118,   nil,   nil,
   118,   118,   118,   118,   118,   118,   118,   nil,   118,   118,
   118,   118,   118,   118,   118,   118,   nil,   118,     3,     3,
   nil,   nil,   nil,     3,   nil,   nil,     3,     3,     3,     3,
     3,     3,     3,     3,   nil,     3,     3,     3,     3,     3,
     3,     3,     3,   nil,     3,    48,    48,   nil,   nil,   nil,
    48,   nil,   nil,   nil,    48,    48,    48,    48,    48,    48,
    48,   nil,    48,    48,    48,    48,    48,    48,    48,    48,
    49,    48,   nil,   nil,   nil,    49,   nil,    49,   nil,    49,
    49,    49,    49,    49,    49,    49,   nil,    49,    49,    49,
    49,    49,    49,    49,    49,   128,    49,   nil,   nil,   nil,
   128,   128,   nil,   nil,   128,   128,   128,   128,   128,   128,
   128,   nil,   128,   128,   128,   128,   128,   128,   128,   128,
   112,   128,   nil,   nil,   nil,   112,   112,   nil,   nil,   112,
   112,   112,   112,   112,   112,   112,   nil,   112,   112,   112,
   112,   112,   112,   112,   112,   116,   112,   nil,   nil,   nil,
   116,   nil,   116,   nil,   116,   116,   116,   116,   116,   116,
   116,   nil,   116,   116,   116,   116,   116,   116,   116,   116,
   nil,   116,    47,    47,   nil,   nil,   nil,    47,   nil,   nil,
   nil,    47,    47,    47,    47,    47,    47,    47,   nil,    47,
    47,    47,    47,    47,    47,    47,    47,    51,    47,   nil,
   nil,   nil,    51,   nil,    51,   nil,    51,    51,    51,    51,
    51,    51,    51,   nil,    51,    51,    51,    51,    51,    51,
    51,    51,    60,    51,   nil,   nil,   nil,    60,    60,   nil,
   nil,    60,    60,    60,    60,    60,    60,    60,   nil,    60,
    60,    60,    60,    60,    60,    60,    60,    57,    60,   nil,
   nil,   nil,    57,    57,   nil,   nil,    57,    57,    57,    57,
    57,    57,    57,   nil,    57,    57,    57,    57,    57,    57,
    57,    57,   nil,    57,    59,    59,   nil,   nil,   nil,    59,
   nil,   nil,   nil,    59,    59,    59,    59,    59,    59,    59,
   nil,    59,    59,    59,    59,    59,    59,    59,    59,    56,
    59,   nil,   nil,    56,    56,   nil,   nil,   nil,    56,    56,
    56,    56,    56,    56,    56,   nil,    56,    56,    56,    56,
    56,    56,    56,    56,    62,    56,   nil,   nil,   nil,    62,
   nil,   nil,   nil,    62,    62,    62,    62,    62,    62,    62,
   nil,    62,    62,    62,    62,    62,    62,    62,    62,    54,
   nil,   nil,   nil,   nil,    54,   nil,   nil,   nil,    54,    54,
    54,    54,    54,    54,    54,   nil,    54,    54,    54,    54,
    54,    54,    54,    54,    52,   nil,   nil,   nil,   nil,    52,
   nil,   nil,   nil,    52,    52,    52,    52,    52,    52,    52,
   nil,    52,    52,    52,    52,    52,    52,    73,   nil,   nil,
   nil,   nil,    73,   nil,   nil,   nil,    73,    73,    73,    73,
    73,    73,    73,   nil,    70,    73,    73,    73,    73,    70,
   nil,   nil,   nil,    70,    70,    70,    70,    70,    70,    70,
   nil,    72,    70,    70,    70,    70,    72,   nil,   nil,   nil,
    72,    72,    72,    72,    72,    72,    72,   nil,    69,    72,
    72,    72,    72,    69,   nil,   nil,   nil,    69,    69,    69,
    69,    69,    69,    69,   nil,    68,    69,    69,    69,    69,
    68,   nil,   nil,   nil,    68,    68,    68,    68,    68,    68,
    68,   nil,    67,    68,    68,    68,    68,    67,   nil,   nil,
   nil,    67,    67,    67,    67,    67,    67,    67,   nil,   nil,
    67,    67,    67,    67 ]

racc_action_pointer = [
    -6,    30,   nil,  1305,   -23,   130,   166,   174,   182,   210,
   218,   nil,   nil,   nil,   nil,   nil,   226,   254,   262,   270,
   298,   306,     3,   370,   nil,   378,   386,   nil,   nil,   414,
   422,   430,   458,   466,   474,   502,   510,   518,   546,   554,
   562,   590,   598,   -15,   634,   662,   nil,  1459,  1332,  1357,
  1194,  1484,  1661,   342,  1636,   nil,  1586,  1534,   nil,  1561,
  1509,   nil,  1611,   nil,    72,    36,   nil,  1769,  1752,  1735,
  1701,   110,  1718,  1684,   138,     2,  1151,   -13,     7,  1253,
   nil,   nil,   nil,   nil,  1115,  1087,  1051,   nil,   nil,   nil,
   nil,  1015,   nil,   100,   951,   943,   907,   885,   842,   814,
   nil,   nil,   nil,   nil,   nil,    15,  1225,   nil,    21,   nil,
   786,   nil,  1407,   778,   770,   734,  1432,   nil,  1278,   nil,
   698,   606,   334,   -37,   nil,   102,    66,   -36,  1382,   nil,
   nil,    18,    30,   979,   nil ]

racc_action_default = [
   -56,   -56,    -1,   -56,   -56,   -56,   -56,   -56,   -56,   -56,
   -56,   -26,   -27,   -28,   -29,   -32,   -56,   -56,   -56,   -56,
   -56,   -56,   -56,   -56,   -12,   -56,   -56,   -35,   -36,   -56,
   -56,   -56,   -56,   -56,   -56,   -56,   -56,   -56,   -56,   -56,
   -56,   -56,   -56,   -56,   -56,   -56,   -13,   -56,   -56,   -56,
   -56,   -56,   -33,   -51,   -52,   -53,   -56,   -56,   135,   -56,
   -56,   -34,   -37,   -38,   -39,   -40,   -41,   -42,   -43,   -44,
   -45,   -46,   -47,   -48,   -49,   -50,   -56,   -15,   -56,   -21,
    -4,   -14,    -5,    -6,   -56,   -56,   -56,   -54,   -55,    -2,
   -31,   -56,   -16,   -56,   -56,   -56,   -56,   -56,   -56,   -56,
    -3,   -17,   -22,   -23,   -24,   -56,   -18,   -20,   -56,    -8,
   -56,   -11,   -56,   -56,   -56,   -56,   -56,   -30,   -56,   -19,
   -56,   -56,   -56,   -56,    -7,   -56,   -56,   -56,   -56,   -10,
   -25,   -56,   -56,   -56,    -9 ]

racc_goto_table = [
     2,    45,    43,    78,    77,     1,    47,    48,    49,    50,
    51,   nil,   101,   nil,   nil,   nil,    52,    53,    54,    55,
    56,    57,   nil,    59,   nil,    60,    61,   nil,   nil,    62,
    63,    64,    65,    66,    67,    68,    69,    70,    71,    72,
    73,    74,    75,   nil,    79,    81,   130,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   107,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    91,   119,   nil,    92,   nil,   nil,   nil,   nil,
    96,   nil,    98,   nil,   nil,    97,   nil,   nil,   nil,   nil,
   nil,    81,   nil,   nil,   106,    79,    81,   nil,    81,   112,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   116,   120,   nil,   118,    79,   nil,   nil,   nil,   126,   nil,
    81,    60,   nil,   nil,   nil,   128,    81,   nil,   133,   nil,
   nil,   nil,   nil,    81 ]

racc_goto_check = [
     2,     5,     4,     7,     6,     1,     3,     3,     3,     3,
     3,   nil,     8,   nil,   nil,   nil,     3,     3,     3,     3,
     3,     3,   nil,     3,   nil,     3,     3,   nil,   nil,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,   nil,     3,     2,     8,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     7,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     5,     7,   nil,     4,   nil,   nil,   nil,   nil,
     5,   nil,     5,   nil,   nil,     3,   nil,   nil,   nil,   nil,
   nil,     2,   nil,   nil,     3,     3,     2,   nil,     2,     3,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     3,     5,   nil,     3,     3,   nil,   nil,   nil,     5,   nil,
     2,     3,   nil,   nil,   nil,     3,     2,   nil,     5,   nil,
   nil,   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,     5,     0,     0,    -2,    -4,   -40,   -41,   -81 ]

racc_goto_default = [
   nil,   nil,    46,     3,   nil,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 56, :_reduce_1,
  4, 57, :_reduce_2,
  5, 57, :_reduce_3,
  3, 57, :_reduce_4,
  3, 57, :_reduce_5,
  3, 57, :_reduce_6,
  8, 57, :_reduce_7,
  5, 57, :_reduce_8,
  13, 57, :_reduce_9,
  9, 57, :_reduce_10,
  5, 57, :_reduce_11,
  2, 57, :_reduce_12,
  1, 60, :_reduce_13,
  2, 60, :_reduce_14,
  2, 59, :_reduce_15,
  3, 59, :_reduce_16,
  3, 61, :_reduce_17,
  3, 62, :_reduce_18,
  5, 62, :_reduce_19,
  3, 62, :_reduce_20,
  1, 62, :_reduce_21,
  1, 63, :_reduce_22,
  1, 63, :_reduce_23,
  1, 63, :_reduce_24,
  6, 63, :_reduce_25,
  1, 58, :_reduce_26,
  1, 58, :_reduce_27,
  1, 58, :_reduce_28,
  1, 58, :_reduce_29,
  7, 58, :_reduce_30,
  4, 58, :_reduce_31,
  1, 58, :_reduce_32,
  2, 58, :_reduce_33,
  3, 58, :_reduce_34,
  2, 58, :_reduce_35,
  2, 58, :_reduce_36,
  3, 58, :_reduce_37,
  3, 58, :_reduce_38,
  3, 58, :_reduce_39,
  3, 58, :_reduce_40,
  3, 58, :_reduce_41,
  3, 58, :_reduce_42,
  3, 58, :_reduce_43,
  3, 58, :_reduce_44,
  3, 58, :_reduce_45,
  3, 58, :_reduce_46,
  3, 58, :_reduce_47,
  3, 58, :_reduce_48,
  3, 58, :_reduce_49,
  3, 58, :_reduce_50,
  2, 58, :_reduce_51,
  2, 58, :_reduce_52,
  2, 58, :_reduce_53,
  3, 58, :_reduce_54,
  3, 58, :_reduce_55 ]

racc_reduce_n = 56

racc_shift_n = 135

racc_token_table = {
  false => 0,
  :error => 1,
  TkComa => 2,
  TkPunto => 3,
  TkPuntoYComa => 4,
  TkDosPuntos => 5,
  TkParAbre => 6,
  TkParCierra => 7,
  TkCorcheteAbre => 8,
  TkCorcheteCierre => 9,
  TkHacer => 10,
  TkAsignacion => 11,
  TkSuma => 12,
  TkResta => 13,
  TkMult => 14,
  TkDiv => 15,
  TkMod => 16,
  TkConjuncion => 17,
  TkDisyuncion => 18,
  TkNegacion => 19,
  TkDesigualdad => 20,
  TkMenor => 21,
  TkMenorIgual => 22,
  TkMayor => 23,
  TkMayorIgual => 24,
  TkIgual => 25,
  TkSiguienteCar => 26,
  TkAnteriorCar => 27,
  TkValorAscii => 28,
  TkConcatenacion => 29,
  TkShift => 30,
  TkWith => 31,
  TkTrue => 32,
  TkFalse => 33,
  TkVar => 34,
  TkBegin => 35,
  TkEnd => 36,
  TkInt => 37,
  TkWhile => 38,
  TkIf => 39,
  TkChar => 40,
  TkOtherwise => 41,
  TkBool => 42,
  TkCaracter => 43,
  TkArray => 44,
  TkRead => 45,
  TkOf => 46,
  TkPrint => 47,
  TkFor => 48,
  TkStep => 49,
  TkFrom => 50,
  TkTo => 51,
  :UMINUS => 52,
  TkNum => 53,
  TkId => 54 }

racc_nt_base = 55

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\",\"",
  "\".\"",
  "\";\"",
  "\":\"",
  "\"(\"",
  "\")\"",
  "\"[\"",
  "\"]\"",
  "\"->\"",
  "\"<-\"",
  "\"+\"",
  "\"-\"",
  "\"*\"",
  "\"\\\\/\"",
  "\"%\"",
  "\"\\\\/\\\\\"",
  "\"\\\\\\\\/\"",
  "\"not\"",
  "\"/=\"",
  "\"<\"",
  "\"<=\"",
  "\">\"",
  "\">=\"",
  "\"=\"",
  "\"++\"",
  "\"--\"",
  "\"#\"",
  "\"::\"",
  "\"$\"",
  "\"with\"",
  "\"true\"",
  "\"false\"",
  "\"var\"",
  "\"begin\"",
  "\"end\"",
  "\"int\"",
  "\"while\"",
  "\"if\"",
  "\"char\"",
  "\"otherwise\"",
  "\"bool\"",
  "\"caracter\"",
  "\"array\"",
  "\"read\"",
  "\"of\"",
  "\"print\"",
  "\"for\"",
  "\"step\"",
  "\"from\"",
  "\"to\"",
  "UMINUS",
  "\"num\"",
  "\"id\"",
  "$start",
  "Programa",
  "Instruccion",
  "Expresion",
  "LDeclaraciones",
  "Instrucciones",
  "Declaracion",
  "Argumentos",
  "Tipo" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'Parser.y', 94)
  def _reduce_1(val, _values, result)
    result = Programa.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 97)
  def _reduce_2(val, _values, result)
      result = Asignacion.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 98)
  def _reduce_3(val, _values, result)
     result = WBloque.new(val[1], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 99)
  def _reduce_4(val, _values, result)
      result = Bloque.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 100)
  def _reduce_5(val, _values, result)
      result = Read.new(val[1])  
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 101)
  def _reduce_6(val, _values, result)
      result = Print.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 103)
  def _reduce_7(val, _values, result)
     result = IfOtherEnd.new(val[1], val[3], val[6])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 104)
  def _reduce_8(val, _values, result)
     result = IfEnd.new(val[1], val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 107)
  def _reduce_9(val, _values, result)
    result = Iteracion_DetStep.new(val[1],val[3], val[5], val[8], val[11])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 109)
  def _reduce_10(val, _values, result)
    result = Iteracion_Det.new(val[1],val[3], val[5], val[7])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 111)
  def _reduce_11(val, _values, result)
     result = Iteracion_Indet.new(val[1], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 112)
  def _reduce_12(val, _values, result)
     result = val[0]           
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 115)
  def _reduce_13(val, _values, result)
     result = val[0]           
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 116)
  def _reduce_14(val, _values, result)
     result = Instrucciones.new(val[0] , val[1])  
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 119)
  def _reduce_15(val, _values, result)
     result = LDeclaracionS.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 120)
  def _reduce_16(val, _values, result)
     result = LDeclaracionRec.new(val[1], val[2] )
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 123)
  def _reduce_17(val, _values, result)
     result = Declaracion.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 126)
  def _reduce_18(val, _values, result)
     result = Argumento.new(val[0] , val[2], nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 127)
  def _reduce_19(val, _values, result)
     result = Argumento.new(val[0] , val[2] , val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 128)
  def _reduce_20(val, _values, result)
     result = ArgumentoId.new(val[0] , val[2], nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 129)
  def _reduce_21(val, _values, result)
     result = Argumento.new(val[0] , nil, nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 132)
  def _reduce_22(val, _values, result)
     result = Int.new() 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 133)
  def _reduce_23(val, _values, result)
     result = Bool.new() 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 134)
  def _reduce_24(val, _values, result)
     result = Char.new()       
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 135)
  def _reduce_25(val, _values, result)
     result = Matriz.new(val[2], val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 138)
  def _reduce_26(val, _values, result)
     result = Entero.new(val[0].contenido)         
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 139)
  def _reduce_27(val, _values, result)
     result = True.new()                 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 140)
  def _reduce_28(val, _values, result)
     result = False.new()                
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 141)
  def _reduce_29(val, _values, result)
     result = Letra.new(val[0].contenido )       
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 142)
  def _reduce_30(val, _values, result)
     result = ValorMatriz.new(val[0],val[2],val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 143)
  def _reduce_31(val, _values, result)
     result = ValorArreglo.new(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 144)
  def _reduce_32(val, _values, result)
     result = Variable.new(val[0].contenido)       
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 145)
  def _reduce_33(val, _values, result)
     result = ValorAscii.new(val[0])     
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 146)
  def _reduce_34(val, _values, result)
     result = Modulo.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 147)
  def _reduce_35(val, _values, result)
     result = SiguienteCar.new(val[0])   
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 148)
  def _reduce_36(val, _values, result)
     result = AnteriorCar.new(val[0])    
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 149)
  def _reduce_37(val, _values, result)
     result = Concatenacion.new(val[0], val[2])   
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 150)
  def _reduce_38(val, _values, result)
     result = Multiplicacion.new(val[0], val[2])  
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 151)
  def _reduce_39(val, _values, result)
     result = Suma.new(val[0], val[2])            
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 152)
  def _reduce_40(val, _values, result)
     result = Resta.new(val[0], val[2])           
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 153)
  def _reduce_41(val, _values, result)
     result = Division.new(val[0], val[2])        
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 154)
  def _reduce_42(val, _values, result)
     result = Desigualdad.new(val[0], val[2])     
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 155)
  def _reduce_43(val, _values, result)
     result = Menor.new(val[0], val[2])           
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 156)
  def _reduce_44(val, _values, result)
     result = MenorIgual.new(val[0], val[2])      
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 157)
  def _reduce_45(val, _values, result)
     result = Igual.new(val[0], val[2])           
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 158)
  def _reduce_46(val, _values, result)
     result = Punto.new(val[0], val[2])   
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 159)
  def _reduce_47(val, _values, result)
     result = Mayor.new(val[0], val[2])           
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 160)
  def _reduce_48(val, _values, result)
     result = MayorIgual.new(val[0], val[2])      
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 161)
  def _reduce_49(val, _values, result)
     result = And.new(val[0], val[2])     
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 162)
  def _reduce_50(val, _values, result)
     result = Or.new(val[0], val[2])      
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 163)
  def _reduce_51(val, _values, result)
     result = Not.new(val[1])             
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 164)
  def _reduce_52(val, _values, result)
     result = Shift.new(val[1])           
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 165)
  def _reduce_53(val, _values, result)
     result = MenosUnario.new(val[1])    
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 166)
  def _reduce_54(val, _values, result)
     result = val[1]                       
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 167)
  def _reduce_55(val, _values, result)
     result = val[1]                       
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
